# Generated by Django 4.2 on 2023-05-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_actor_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер залу')),
                ('stage', models.IntegerField(verbose_name='Етаж')),
                ('places', models.IntegerField(verbose_name='Кіл-ть місць')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Зали',
            },
        ),
        migrations.CreateModel(
            name='Hall_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип залу')),
            ],
            options={
                'verbose_name': 'Тип залу',
                'verbose_name_plural': 'Тип залів',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Імʼя клієнта')),
                ('place_num', models.IntegerField(verbose_name='Місце')),
                ('paid', models.BooleanField(verbose_name='Оплачено')),
                ('date_resevation', models.DateTimeField(verbose_name='Дата та час')),
            ],
            options={
                'verbose_name': 'Резервація',
                'verbose_name_plural': 'Резервації',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Тривалість'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Початок')),
                ('end', models.DateTimeField(verbose_name='Кінець')),
                ('hall_id', models.ManyToManyField(to='cinema.hall', verbose_name='Зал')),
                ('movie_id', models.ManyToManyField(to='cinema.movie', verbose_name='Фільм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеанси',
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.hall_type', verbose_name='Тип залу'),
        ),
    ]
