# Generated by Django 4.2 on 2023-05-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_session_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='hall_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='session',
            name='hall_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.hall', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='session',
            name='movie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.movie', verbose_name='Фільм'),
        ),
    ]
