# Generated by Django 4.2 on 2023-05-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_reservation_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.session', verbose_name='Сеанс'),
        ),
    ]
