# Generated by Django 4.2 on 2023-05-23 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_reservation_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_resevation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
