# Generated by Django 4.2 on 2023-05-24 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_alter_reservation_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Імʼя клієнта'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_resevation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата та час'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(blank=True, default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place_num',
            field=models.IntegerField(blank=True, verbose_name='Місце'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.session', verbose_name='Сеанс'),
        ),
    ]
