# Generated by Django 4.2 on 2023-05-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_reservation_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Імʼя клієнта'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place_num',
            field=models.IntegerField(verbose_name='Місце'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinema.session', verbose_name='Сеанс'),
        ),
    ]
