# Generated by Django 4.2 on 2023-05-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_reservation_place_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='available',
            field=models.BooleanField(default=0, verbose_name='Доступний'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='future',
            field=models.BooleanField(default=0, verbose_name='Майбутні'),
            preserve_default=False,
        ),
    ]
